### ISSUE TITLE
Question about downloading Multiplatform Photogrammetry Dataset

### ISSUE THREAD

**Issue by VictorZoo** [whuwuteng/EuroSDR_UAV_Micmac#1]
Hi,

Rencently I got the problem to downloading the Multiplatform Photogrammetry Dataset. When I open the website in the .pdf, it turn out the blank and have nothing.

How do you dowload this dataset? Could you help me to click the link and have a look? Because I dont know whether is my poor WIFI or not.

Thanks a lot!

**Comment by whuwuteng** [comment]
Hello, I downloaded the dataset from the URL in the document. I have checked the URL in https://github.com/whuwuteng/EuroSDR_UAV_Micmac/blob/master/document/description_and_download_links_v3.pdf, I think it works.
Maybe you need to check it again.
Best.
